name: Parse JSON from file
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'centos:7'

    steps:
    - name: nodejs20
      run: |
           curl -o node-v20.17.0-linux-x64-glibc-217.tar.xz https://unofficial-builds.nodejs.org/download/release/v20.17.0/node-v20.17.0-linux-x64-glibc-217.tar.xz
           tar xvf node-v20.17.0-linux-x64-glibc-217.tar.xz
           cp node-v20.17.0-linux-x64-glibc-217/bin/node /__e/node20/bin/node

    - name: Checkout
      uses: actions/checkout@v4

    - name: Read file
      id: read_file
      run: echo "json=$(tr -d '\n' < deps.json)" >> $GITHUB_OUTPUT

    - name: fromJSON
      run: |
            echo "OR_TOOLS_TAG=${{ steps.read_file.outputs.json && fromJSON(steps.read_file.outputs.json).or-tools }}" >> $GITHUB_ENV

    - name: from env
      run: echo ${{ env.OR_TOOLS_TAG }}
