name: Parse JSON from file

on:
  push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v3

    - name: Read file
      id: read_file
      run: echo "json=$(tr -d '\n' < deps.json)" >> $GITHUB_OUTPUT

    - name: fromJSON
      run: |
            echo ${{ steps.read_file.outputs.json && fromJSON(steps.read_file.outputs.json).or-tools }}
    
    

     
